export const userActionTypes = {
  ASYNC_SIGNUP_USER: 'ASYNC_SIGNUP_USER',
  ASYNC_SIGNIN_USER: 'ASYNC_SIGNIN_USER',
  ASYNC_LOGOUT_USER: 'ASYNC_LOGOUT_USER',
  SET_USER: 'SET_USER',
  LOG_OUT: 'LOG_OUT',
}

export const itemActionTypes = {
  ASYNC_FETCH_DATA: 'ASYNC_FETCH_DATA',
  ASYNC_ADD_ITEM: 'ASYNC_ADD_ITEM',
  ASYNC_EDIT_ITEM: 'ASYNC_EDIT_ITEM',
  ASYNC_REMOVE_ITEM: 'ASYNC_REMOVE_ITEM',
  ASYNC_SELECT_ALL: 'ASYNC_SELECT_ALL',
  ASYNC_REMOVE_SELECTED: 'ASYNC_REMOVE_SELECTED',
  SET_DATA: 'SET_DATA',
  SET_FILTER: 'SET_FILTER',
  SELECT_ALL: 'SELECT_ALL',
}
